frontend/package-lock.json
frontend/package.json
frontend/src/App.js
frontend/src/components/Login.jsx
frontend/src/shared/components/DropdownMenu.jsx
frontend/src/shared/components/InputField.jsx
frontend/src/shared/components/InputForm.jsx
frontend/src/shared/components/dropdownMenu/CustomDropdownMenu.jsx
frontend/src/shared/components/dropdownMenu/StDropdownMenu.jsx
frontend/src/shared/components/input/StInputField.jsx
frontend/src/shared/components/input/StInputForm.jsx
frontend/src/shared/constants/PropertyTypes.js
frontend/src/shared/constants/input/LeaseFormInputs.js
jsconfig.json

https://teammo.atlassian.net/browse/EF-11

Ef 11 input form add a lease

---

frontend/package-lock.json
frontend/package.json
frontend/src/App.css
frontend/src/App.js
frontend/src/components/home/HomeWelcomePage.js
frontend/src/components/home/SideBarItem.css
frontend/src/components/home/SideBarItem.js

@yli0402 's work. pushing her code in this PR as her env was having some issues.

EF-28: Home page

---

frontend/src/App.js
frontend/src/components/home/HomeSideBar.js

Link pages to dashboard for demo

---

.gitignore
server/app.js
server/bin/www
server/package-lock.json
server/package.json
server/routes/index.js
server/routes/users.js

Set up server

---

client/src/components/property/AddPropertyForm.js
client/src/components/property/AmenitiesChoices.js
client/src/components/property/property.css
client/src/components/property/propertyTypes.js
client/src/components/propertyhome/PropertyHome.js

Ability to add a property as well as select multiple amenities from a list of amenities. When property Form is imported in PropertyHome.js, Add worker no longer opens a pop up form. not sure why...

Added Form and multi select

---

client/src/components/propertyhome/TenantView.js
client/src/components/propertyhome/TenantViewCard.js

Added tenant pop up for tenant view page.

Add pop up for tenant view

---

client/src/components/worker/UpdateWorkerFrom.js
client/src/components/worker/WorkerLists.js
client/src/components/worker/workerDetail.js
client/src/redux/workersRedux/workerDetailsReducer.js
client/src/redux/workersRedux/workersReduecer.js
client/src/redux/workersRedux/workersService.js
client/src/redux/workersRedux/workersThunks.js
package-lock.json
server/app.js
server/routes/workers.js

Rebuild the worker with a backend server,
Add an update fun.

Worker more details

---

client/src/components/tenant/LeaseOverviewCard.css
client/src/components/tenant/LeaseOverviewCard.js
client/src/components/tenant/PaymentHistory.js
client/src/components/tenant/RequiredPayments.js
client/src/components/tenant/Tenant.css
client/src/components/tenant/Tenant.js
client/src/components/tenant/TenantOverviewCard.js
client/src/components/tenant/TenantProfileCard.js
client/src/components/tenant/UtilitiesCard.js

Implemented framework for the tenants page. I'm using the following tenant object structure. Have not yet hooked up the tenants view with the tenant page, will need to be done in a later PR.
```
{
"firstName":"Mary",
"lastName":"Jane",
"email":"someone@example.com",
"phoneNumber":"111-222-3333",
"lease":{
"startDate":"2022-01-22",
"endDate":"2022-12-01",
"term":"12 months",
"type":"Month to Month",
"fees":[
{
"type":"Rent",
"amount":1000,
"dueDate":"May 1"
}
]
},
"paymentHistory":[
{
"type":"Rent",
"charge":1000,
"paid":1000,
"date":"2022-01-12"
},
{
"type":"Rent",
"charge":1000,
"paid":1000,
"date":"2022-01-12"
},
{
"type":"Rent",
"charge":1000,
"paid":1000,
"date":"2022-01-12"
}
]
}
```

Implement tenant page

---

server/bin/www
server/models/property.js
server/models/tenant.js

`tenant` model is now keep reference instead of `property`
also fixed the `property` model

Adjust tenant and property model to better fit one to many relation

---

client/src/components/tenant/AddTenantForm.js
client/src/redux/tenants/actionTypes.js
client/src/redux/tenants/reducer.js
client/src/redux/tenants/service.js
client/src/redux/tenants/thunks.js
server/routes/tenants.js

basically just took format from property form and adjusted so it has tenant info. Added tenant route for redux. Not sure if anything actually works but should since its all the same, will do slight debugging if needed. Waiting to discuss with group about some details

tenant form/redux

---

server/routes/properties.js
server/routes/tenants.js

Connected all property endpoints to use DB

Connect property endpoints to db

---

client/src/components/tenant/AddTenantForm.js

imported closeTenantAdd and created function handleCloseForm which calls dispatch(closeTenantADD())

can close add tenant form

---

client/src/components/propertyhome/PropertyDetailCard.css
client/src/components/propertyhome/PropertyHome.css

Adjust location of buttons

---

client/src/components/propertyhome/PropertyHome.js
client/src/components/tenant/AddTenantForm.js
client/src/redux/tenants/tenantService.js
client/src/redux/tenants/tenantsReducer.js
server/models/property.js
server/models/tenant.js

removed tenant list from property schema

Ef 67 and ef 74

---

client/package-lock.json
client/package.json
client/src/redux/config.js
client/src/redux/properties/service.js
client/src/redux/tenants/tenantService.js
client/src/redux/workersRedux/workersService.js

Set up environment variables for deployment.

Set up for deployment

---

client/package-lock.json
client/package.json

Add missing `data-fns` dependency

Added missing dependency

---

client/src/components/tenant/TenantProfileCard.js
client/src/shared/pages/property/ConfirmationModal.js
client/src/shared/pages/property/DeleteConfirmationModal.js
client/src/shared/pages/property/PropertyCardDetails.js
server/routes/tenants.js

Reusing the `Modal` in `PropertyDetailCard` from the property dashboard.

Connect delete button for tenants page

---

client/src/components/tenant/AddTenantForm.js
client/src/components/tenant/TenantProfileCard.js
client/src/redux/tenants/tenantService.js
server/routes/tenants.js

Connect edit button for tenants page

---

client/src/components/property/property.css
client/src/components/propertyhome/TenantViewCard.js
client/src/components/tenant/AddTenantForm.js
client/src/components/tenant/TenantOverviewCard.js
client/src/components/tenant/TenantProfileCard.js
client/src/redux/tenants/service.js
client/src/shared/constants/tenant/LeaseTypes.js
server/models/tenant.js

Made changes to Tenant model/form
Removed all mentions of tenant middle name as it is not part of the model (can just add to first name or something if needed),
Added new input options in tenant form, refactored AddTenantForm to use InputField file. Made lease details required.
Fixed issue with editing
editing did not work, had to change route API to put .../tenants instead of /tenants/tenantID
added dispatch to refresh page when update finishes so page reflects newest information.

Ef 86 tenant form 

---

client/src/components/tenant/PaymentHistory.js
client/src/components/tenant/RequiredPayments.js
client/src/components/tenant/TenantHome.js
client/src/components/tenant/TenantOverviewCard.js
client/src/shared/components/InputField.js
client/src/shared/constants/tenant/RequiredFields.js

Added buttons to add and delete required payments, decided that editing would be too much as there are only 3 fields, and because required payments is such a small box it would look too busy. Fixed issue with Fee Type showing up incorrectly.
Added changes from https://github.com/ryanzhxu/estate-flow/pull/113 as well.

Ef 93 ef 98 required payment fixes

---

client/package-lock.json
client/package.json
client/src/components/Dashboard/Calculator.js
client/src/components/Dashboard/Dashboard.js
client/src/components/Dashboard/ProfitModal.css
client/src/components/Dashboard/ProfitModal.js
client/src/redux/properties/actionTypes.js
client/src/redux/properties/reducer.js
client/src/redux/properties/service.js
client/src/redux/properties/thunks.js
client/src/redux/stats/service.js
server/app.js
server/routes/properties.js
server/routes/stats.js

Implement profit calculator

---

client/src/components/tenant/PaymentHistory.js

added functionality to sort by asc and desc order/ group types. Styling can be added :) rn its just clicking on Date or Type

can sort in asc/desc order

---

client/src/components/tenant/LeaseOverviewCard.css
client/src/components/tenant/LeaseOverviewCard.js
client/src/components/tenant/TenantHome.js

added edit button to lease, added a clickable download button (does nothing)

added edit button to lease

---

server/aws/multer.js
server/aws/s3.js
server/models/database.js
server/models/tenant.js
server/models/worker.js
server/package-lock.json
server/package.json
server/routes/properties.js
server/routes/tenants.js
server/routes/workers.js

Created an AWS S3 instance to store files in the cloud. The files can be referenced via a url, so the schemas for the data can remain the same. 
- Files that are sent through the POST endpoints will be uploaded to AWS. 
- Also implemented functionality to delete associated files in AWS.

Implement cloud storage for files

---

client/src/App.css
client/src/components/Dashboard/Banner.css
client/src/components/Dashboard/Banner.js
client/src/components/Dashboard/Dashboard.js

added banner to dashboard

---

client/src/shared/services/LeasePdfUtils.js

edited lease pdf

---

client/src/components/propertyhome/PropertyHome.js
server/models/tenant.js

removed lease file from schema and form

removed option to upload

---

client/src/components/Dashboard/Calculator.css
client/src/components/Dashboard/Calculator.js
client/src/components/Dashboard/Calendar.css
client/src/components/Dashboard/Dashboard.js
client/src/components/home/SideBarItem.css

issue with font looking different based on OS

Changed font of dashboard

---

client/src/components/ImageUploader.js
client/src/components/property/PropertyCardDetails.js
client/src/components/propertyhome/PropertyHome.js
client/src/components/propertyhome/TenantView.js
client/src/components/tenant/TenantProfileCard.js
client/src/redux/properties/service.js
client/src/redux/tenants/reducer.js
client/src/redux/tenants/service.js
client/src/shared/components/InputFormModal.js
client/src/shared/services/Helpers.js
server/models/tenant.js
server/routes/properties.js
server/routes/tenants.js

Connected image uploader for the edit tenant and edit property forms.

Connect image uploader to edit forms

---

client/src/components/propertyhome/PropertyHome.js
client/src/components/tenant/TenantProfileCard.js
server/routes/properties.js

Fix property image uploader bug

Fix image uploader bug for property edit form
